dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.2
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.2'
dotenv: .env
networks:
  default: development
  mainnet-fork-dev:
    verify: False
    from_key: ${MAINNET_FORK_PRIVATE_KEY}
  sepolia:
    verify: True
    from_key: ${SEPOLIA_PRIVATE_KEY}
  goerli:
    verify: True
    from_key: ${GOERLI_PRIVATE_KEY}
  ganache-local:
    verify: False
    from_key: ${GANACHE_UI_PRIVATE_KEY}